#!/usr/bin/env node
/**
 * Regenerate examples/: one Markdown report, JSON report and share card per
 * site in examples/sites.json. Run after `pnpm build`.
 *
 *   node scripts/examples.mjs            # static checks only
 *   node scripts/examples.mjs --render   # with the rendered comparison
 */
import { execFile } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const exec = promisify(execFile);
const render = process.argv.includes("--render");
const root = fileURLToPath(new URL("..", import.meta.url));
const cli = join(root, "dist", "cli.js");
const sites = JSON.parse(await readFile(join(root, "examples", "sites.json"), "utf8"));

const index = ["# Examples", "", "Reports generated by `npx ai-readable` on public pages. Regenerate with `pnpm examples`.", "", "| Site | Score | Search & assistant bots blocked | Report |", "|---|---:|---|---|"];

for (const site of sites) {
  const slug = site.url.replace(/^https?:\/\//, "").replace(/[^a-z0-9]+/gi, "-").replace(/-+$/, "").toLowerCase();
  const dir = join(root, "examples", slug);
  await mkdir(dir, { recursive: true });
  const args = [cli, site.url, "--json", "--card", join(dir, "card.svg")];
  if (render) args.push("--render");
  process.stderr.write(`${site.url}\n`);
  const { stdout } = await exec(process.execPath, args, { env: { ...process.env, NO_COLOR: "1" } });
  const report = JSON.parse(stdout);
  await writeFile(join(dir, "report.json"), `${JSON.stringify(report, null, 2)}\n`);
  const md = await exec(process.execPath, [cli, site.url, "--md", ...(render ? ["--render"] : [])], { env: { ...process.env, NO_COLOR: "1" } });
  await writeFile(join(dir, "README.md"), `${md.stdout.trim()}\n\n![share card](./card.svg)\n`);
  const blocked = report.bots.filter((b) => b.category !== "training" && !b.allowed).map((b) => b.name);
  const score = report.fetchError ? `fetch failed: ${report.fetchError}` : String(report.score);
  index.push(`| ${site.url.replace(/^https?:\/\//, "")} | ${score} | ${blocked.length ? blocked.join(", ") : "none"} | [report](./${slug}/README.md) |`);
}

await writeFile(join(root, "examples", "README.md"), `${index.join("\n")}\n`);
process.stderr.write("examples/README.md written\n");
